### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by yrcrcy** [melhousni/DSMNet#1]
Thank you for your contribution

Excuse me, but I have a question want to ask: I downloaded you provide training and validation data sets, in accordance with your command execution "python test_dsm. Py Vaihingen False", the output of the output folder, why do I get the gray image, rather than the color images in your thesis, how can do I need to get the color image, thank you for your reply, thank you!

**Comment by melhousni** [comment]
Hi,
The grayscale output that gets saved is the height prediction results. If you are talking about the segmentation results you should check [here](https://github.com/melhousni/DSMNet/blob/b6fddcda88b05009a0349f8c2ace8fb104a7a6c0/test_dsm.py#L99), where you can find the height, semantic and surface normals predictions.
